## Import deps

In [ ]:
!pip install -U datasets mlable tokun llaminate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 15.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 16.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.5/239.5 kB 23.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.3/124.3 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.6/301.6 kB 25.3 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting un

In [ ]:
!huggingface-cli login # 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

%load_ext tensorboard


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible): 
Add token as git credential? (Y/n) n
Token is valid (permission: read).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [ ]:
import datetime
import functools
import itertools
import math
import os
import random
import urllib.request

import datasets as ds
import tensorflow as tf
import tensorflow_datasets as tfds

import mlable.data
import mlable.io
import mlable.metrics
import mlable.optimizers

import tokun.data
import tokun.evaluation
import tokun.meta
import tokun.pipeline
import tokun.model

import llaminate.model
import llaminate.pipeline
import llaminate.utils

In [ ]:
print("Tensorflow version " + tf.__version__)

Tensorflow version 2.15.0


## Setup the GPU / TPU

In [ ]:
tf.debugging.set_log_device_placement(False)

CPU = tf.config.list_logical_devices('CPU')
GPU = tf.config.list_logical_devices('GPU')
TPU = tf.config.list_logical_devices('TPU')

if TPU:
    RESOLVER = tf.distribute.cluster_resolver.TPUClusterResolver()
    tf.config.experimental_connect_to_cluster(RESOLVER)
    tf.tpu.experimental.initialize_tpu_system(RESOLVER)
    DISTRIBUTION_STRATEGY = tf.distribute.TPUStrategy(RESOLVER)
elif GPU:
    DISTRIBUTION_STRATEGY = tf.distribute.MirroredStrategy(GPU)
else:
    DISTRIBUTION_STRATEGY = tf.distribute.MirroredStrategy(CPU)

print(DISTRIBUTION_STRATEGY)

## Mode

In [ ]:
# TOGGLE ######################################################################

IMPORT = False
FREEZE = True # freeze tokun weights
TRAINING = True
DEBUG = False

## Defining The Metadata

In [ ]:
# MODEL PARAMETERS ############################################################

N_SEQUENCE_AXIS = 1
N_FEATURE_AXIS = -1

N_LAYERS_NUM = 8
N_HEADS_NUM = 4

N_BATCH_DIM = 128
N_CACHE_DIM = 256 # 2048 in llama3-8B but tokun embeddings = 16 chr = 4 llama3 tokens
N_EMBED_DIM = 256
N_HIDDEN_DIM = 4 * N_EMBED_DIM
N_HEAD_DIM = N_EMBED_DIM // N_HEADS_NUM

LLAMINATE_PATH = 'llaminate.keras'

In [ ]:
# TOKENIZER PARAMETERS ########################################################

TOKUN_DIM = [4, 16]
TOKUN_FACTOR = math.prod(TOKUN_DIM) // 4
TOKUN_VERSION = tokun.meta.version(units=TOKUN_DIM, axis=1)

TOKUN_LABEL = '6.3'
TOKUN_PATH = 'tokun.keras'
TOKUN_URL = 'https://github.com/apehex/tokun/raw/main/models/{}/{}/{}.keras'.format(*TOKUN_VERSION, TOKUN_LABEL)

In [ ]:
# TRAINING PARAMETERS #########################################################

N_SAMPLE_DIM = N_CACHE_DIM * TOKUN_FACTOR

N_EPOCHS = 8
N_EPOCHS_RAMPUP = 0
N_EPOCHS_SUSTAIN = 0

R_MIN, R_MAX, R_EXP = (0.1 if IMPORT else 1.) * 0.001 * 0.001, (0.1 if IMPORT else 1.) * 0.1 * 0.001, 0.8

CLASS_WEIGHTS = {__c: 0.3 if __c == 0 else 1. for __c in range(N_ENCODING_DIM)} # there are 3 times more 0s than other bytes

In [ ]:
# DERIVED PARAMETERS ##########################################################

DATETIME = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

LLAMINATE_VERSION = [str(N_LAYERS_NUM), str(N_HIDDEN_DIM)]
LLAMINATE_LOGS_PATH = os.path.join('.logs/', *LLAMINATE_VERSION, DATETIME)
LLAMINATE_MODEL_PATH = 'llaminate.keras'

## Loading The Data

In [ ]:
# META ########################################################################

# TODO bigcode/the-stack
# TODO ArmelR/stack-exchange-instruction

DATASETS_META = {
    'pt-wikipedia': {
        'path': 'wikimedia/wikipedia',
        'name': '20231101.en',
        'train': 'train[:90%]',
        'test': 'train[-10%:]',
        'features': ['text'],},
    'ft-retro-ascii-art': {
        'path': 'jdpressman/retro-ascii-art-v1',
        'name': None,
        'train': 'train',
        'test': 'validation',
        'features': ['prompt', 'art_aic'],},
    'ft-stack-exchange': {
        'path': 'Alignment-Lab-AI/Stack-Exchange-April',
        'name': None,
        'train': 'train[:90%]',
        'test': 'train[-10%:]',
        'features': ['question', 'answer'],},
    'ft-math': {
        'path': 'hendrycks/competition_math',
        'name': None,
        'train': 'train',
        'test': 'test',
        'features': ['problem', 'solution'],},}

In [ ]:
# DOWNLOAD ####################################################################

DATASETS = {
    __name: {
        'train': ds.load_dataset(path=__args['path'], name=__args['name'], split=__args['train']).to_tf_dataset(shuffle=True, batch_size=None),
        'test': ds.load_dataset(path=__args['path'], name=__args['name'], split=__args['test']).to_tf_dataset(shuffle=True, batch_size=None),}
    for __name, __args in DATASETS_META.items()}

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/6407814 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/33 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/41 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/5894 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/300 [00:00<?, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

The repository for hendrycks/competition_math contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/hendrycks/competition_math.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


Generating train split:   0%|          | 0/7500 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5000 [00:00<?, ? examples/s]

## Testing The Data

In [ ]:
# STATS #######################################################################

STATS = {__n: {'min': 0, 'max': 0, 'mean': 0} for __n in DATASETS}

for __name in DATASETS:
    # sample each dataset
    __m = DATASETS_META[__name]
    __b = iter(DATASETS[__name]['train'])
    __s = [next(__b) for _ in range(128)]
    __l = [len(tf.strings.join(inputs=[__e[__f] for __f in __m['features']], separator='\x1d').numpy()) for __e in __s]
    # save the stats
    STATS[__name]['min'] = min(__l)
    STATS[__name]['max'] = max(__l)
    STATS[__name]['mean'] = tf.reduce_mean(__l).numpy()

In [ ]:
print(STATS)

{'pt-wikipedia': {'min': 155, 'max': 26935, 'mean': 2231}, 'ft-retro-ascii-art': {'min': 3073, 'max': 3249, 'mean': 3149}, 'ft-stack-exchange': {'min': 254, 'max': 7128, 'mean': 1749}, 'ft-math': {'min': 132, 'max': 4478, 'mean': 764}}


In [ ]:
__b = iter(DATASETS['ft-stack-exchange']['train'])

In [ ]:
__s = next(__b)
tf.strings.join(inputs=[__s['question'], __s['answer']], separator='\x1d')

TypeError: tuple indices must be integers or slices, not str

## Training Metrics

In [ ]:
# METRICS #####################################################################

with DISTRIBUTION_STRATEGY.scope():
    byte_accuracy = mlable.metrics.CategoricalGroupAccuracy(group=1, name='byte_accuracy')
    character_accuracy = mlable.metrics.CategoricalGroupAccuracy(group=4, name='character_accuracy')
    token_accuracy = mlable.metrics.CategoricalGroupAccuracy(group=math.prod(TOKUN_DIM), name='token_accuracy')

## Loading The Tokenizer

In [ ]:
# IMPORT ######################################################################

urllib.request.urlretrieve(TOKUN_URL, TOKUN_PATH)

# INIT ########################################################################

with DISTRIBUTION_STRATEGY.scope():
    TOKUN = tf.keras.models.load_model(TOKUN_PATH)
    TOKUN.trainable = not FREEZE # freeze the weights
    TOKUN.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=R_MAX),
        loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False, label_smoothing=0., axis=-1, reduction=tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE, name='loss'),
        metrics=[byte_accuracy, character_accuracy, token_accuracy])

## Initializing The Model

In [ ]:
# DEBUG MODEL #################################################################

class DebugModel(tf.keras.Sequential):
    def __init__(self, **kwargs) -> None:
        super(DebugModel, self).__init__(
            layers=[
                tf.keras.layers.Embedding(
                    input_dim=N_EMBED_DIM,
                    output_dim=N_EMBED_DIM,
                    embeddings_initializer='glorot_uniform',
                    name='embed-1')])


In [ ]:
# WEIGHTS #####################################################################

with DISTRIBUTION_STRATEGY.scope():
    # load or init the weights
    if IMPORT and os.path.isfile(LLAMINATE_MODEL_PATH):
        LLAMINATE = tf.keras.models.load_model(LLAMINATE_MODEL_PATH)
    else:
        LLAMINATE = llaminate.model.Transformer(num_layers=N_LAYERS_NUM, num_heads=N_HEADS_NUM, cache_dim=N_CACHE_DIM, embed_dim=N_EMBED_DIM, head_dim=N_HEAD_DIM, hidden_dim=N_HIDDEN_DIM)

In [ ]:
# INIT ########################################################################

with DISTRIBUTION_STRATEGY.scope():
    # load the tokenizer
    LLAMINATE.set_tokenizer(encoder=TOKUN._encoder, decoder=TOKUN._decoder)
    # simpler model to debug
    if DEBUG: LLAMINATE = DebugModel()

In [ ]:
# COMPILE #####################################################################

with DISTRIBUTION_STRATEGY.scope():
    LLAMINATE.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=R_MAX),
        loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False, label_smoothing=0., axis=-1, reduction=tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE, name='loss'),
        metrics=[byte_accuracy, character_accuracy, token_accuracy])


## Preprocess

In [ ]:
# ITERATE #####################################################################

for __name in DATASETS:
    DATASETS[__name]['train'] = llaminate.pipeline.preprocess(dataset=DATASETS[__name]['train'], token_dim=math.prod(TOKUN_DIM), embed_dim=N_EMBED_DIM, sample_dim=N_SAMPLE_DIM, features=DATASETS_META[__name]['features'])
    DATASETS[__name]['test'] = llaminate.pipeline.preprocess(dataset=DATASETS[__name]['test'], token_dim=math.prod(TOKUN_DIM), embed_dim=N_EMBED_DIM, sample_dim=N_SAMPLE_DIM, features=DATASETS_META[__name]['features'])

In [ ]:
# CONCATENATE #################################################################

DATASET_TRAIN = functools.reduce(lambda __l, __r: __l.concatenate(__r), [DATASETS[__n]['train'] for __n in (set(DATASETS.keys()) - {'ft-retro-ascii-art'})]) # - {'pt-wikipedia'}
DATASET_TEST = functools.reduce(lambda __l, __r: __l.concatenate(__r), [DATASETS[__n]['test'] for __n in (set(DATASETS.keys()) - {'ft-retro-ascii-art'})]) # - {'pt-wikipedia'}

In [ ]:
# CHECK DATASET ###############################################################

print(DATASET_TRAIN.element_spec)
print(DATASET_TEST.element_spec)

(TensorSpec(shape=(16384,), dtype=tf.uint8, name=None), TensorSpec(shape=(16384, 256), dtype=tf.float32, name=None))
(TensorSpec(shape=(16384,), dtype=tf.uint8, name=None), TensorSpec(shape=(16384, 256), dtype=tf.float32, name=None))


In [ ]:
__b = iter(DATASET_TEST.batch(N_BATCH_DIM))

In [ ]:
__x, __y = next(__b)
LLAMINATE(__x, training=True).shape

<tf.Tensor: shape=(128, 16384, 256), dtype=float32, numpy=
array([[[9.92202163e-01, 4.93603523e-08, 1.36473645e-07, ...,
         7.72985231e-10, 6.83994529e-07, 2.24303398e-09],
        [9.99779463e-01, 1.71575084e-04, 4.07853085e-09, ...,
         8.63630945e-09, 4.08796859e-06, 1.75682767e-11],
        [4.14049191e-06, 6.01124039e-09, 3.06056742e-11, ...,
         3.52065155e-10, 4.69993154e-07, 2.07445216e-12],
        ...,
        [2.63491296e-04, 1.32965479e-14, 9.99728322e-01, ...,
         3.81397891e-09, 9.12464982e-13, 1.17737495e-11],
        [5.84754171e-16, 2.59493937e-09, 8.05685813e-14, ...,
         8.64969012e-13, 3.37133513e-16, 4.53963126e-12],
        [1.11002008e-13, 9.33785723e-15, 2.47736676e-21, ...,
         7.48807777e-16, 2.86997578e-11, 1.76315890e-16]],

       [[9.92202163e-01, 4.93603523e-08, 1.36473645e-07, ...,
         7.72985231e-10, 6.83994529e-07, 2.24303398e-09],
        [9.99779463e-01, 1.71575084e-04, 4.07853085e-09, ...,
         8.63630945e-09,

In [ ]:
LLAMINATE.summary()

Model: "debug_model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embed-1 (Embedding)         (None, None, 256)         65536     
                                                                 
Total params: 65536 (256.00 KB)
Trainable params: 65536 (256.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Train

In [ ]:
# CALLBACKS ###################################################################

lr_callback = tf.keras.callbacks.LearningRateScheduler(functools.partial(mlable.optimizers.learning_rate_hokusai, lr_min=R_MIN, lr_max=R_MAX, lr_exp=R_EXP, rampup=N_EPOCHS_RAMPUP, sustain=N_EPOCHS_SUSTAIN), verbose=True)
cp_callback = tf.keras.callbacks.ModelCheckpoint(LLAMINATE_MODEL_PATH, monitor='val_loss', verbose=1, save_best_only=True, save_weights_only=False, mode='auto', save_freq='epoch')
tb_callback = tf.keras.callbacks.TensorBoard(log_dir=LLAMINATE_LOGS_PATH)

In [ ]:
# TRAIN #######################################################################

if TRAINING:
    with DISTRIBUTION_STRATEGY.scope():
        TRAINING_HISTORY = LLAMINATE.fit(
          x=DATASET_TRAIN.batch(N_BATCH_DIM).prefetch(tf.data.AUTOTUNE),
            batch_size=None,
            epochs=N_EPOCHS,
            validation_split=None,
            validation_data=DATASET_TEST.batch(N_BATCH_DIM).prefetch(tf.data.AUTOTUNE),
            validation_freq=list(range(1, N_EPOCHS + 1, 1)),
            class_weight=CLASS_WEIGHTS,
            verbose=1,
            callbacks=[lr_callback, cp_callback, tb_callback])


Epoch 1: LearningRateScheduler setting learning rate to 0.0001.
Epoch 1/8
   25/73680 [..............................] - ETA: 32:02:13 - loss: 11.7378 - accuracy: 0.4361

KeyboardInterrupt: 

## Export

## Dataviz

In [ ]:
# DATA ########################################################################

SAMPLES = [
    """위키백과, 우리 모두의 백과사전.\nt-분포 확률적 임베딩(t-SNE)은 데이터의 차원 축소에 사용되는 기계 학습 알고리즘 중 하나로, 2002년 샘 로이스Sam Rowise와 제프리 힌튼에 의해 개발되었다.[1] t-SNE는 비선형 차원 축소 기법으로, 고차원 데이터를 특히 2, 3차원 등으로 줄여 가시화하는데에 유용하게 사용된다. 구체적으로 t-SNE는 비슷한 데이터는 근접한 2, 3차원의 지점으로, 다른 데이터는 멀리 떨어진 지점으로 맵핑한다.""",
    """class Encoder(tf.keras.models.Model):\n    def __init__(self, depth: int, token_dim: int, encoding_dim: int, embedding_dim: int, latent_dim: int, batch_dim: int=None, attention: bool=False, **kwargs) -> None:\n        super(Encoder, self).__init__(**kwargs)\n        self._encoder = tf.keras.Sequential([\n            tf.keras.Input(shape=(encoding_dim,), batch_size=batch_dim, name='input'), # (B * G ^ D, U)\n            tf.keras.layers.Dense(units=embedding_dim, activation=None, use_bias=False, kernel_initializer='glorot_uniform', bias_initializer=None, name='embed-1'),] # (B * G ^ D, U) => (B * G ^ D, E)\n            + [tokun.layers.TokenizeBlock(left_axis=-2, right_axis=-1, token_dim=token_dim, latent_dim=latent_dim, attention=attention, name='tokenize' + (__i + 1) * '-4') for __i in range(depth)]) # (B * G ^ i, E) => (B * G ^ (i-1), E)\n\n    def call(self, x: tf.Tensor) -> tf.Tensor:\n        return self._encoder(x)\n""",
    """class AutoEncoder(tf.keras.models.Model):\n    def __init__(self, token_dim: int, encoding_dim: int, embedding_dim: int, latent_dim: int, batch_dim: int=None, **kwargs) -> None:\n        super(AutoEncoder, self).__init__(**kwargs)\n        self._encoder = Encoder(token_dim=token_dim, encoding_dim=encoding_dim, embedding_dim=embedding_dim, latent_dim=latent_dim, batch_dim=batch_dim)\n        self._decoder = Decoder(token_dim=token_dim, encoding_dim=encoding_dim, embedding_dim=embedding_dim, latent_dim=latent_dim, batch_dim=batch_dim)\n\n    def call(self, x: tf.Tensor) -> tf.Tensor:\n        return self._decoder(self._encoder(x))""",
    """class AutoEncoder(tf.keras.models.Model):\n  def __init__(self, token_dim: int, encoding_dim: int, embedding_dim: int, latent_dim: int, batch_dim: int=None, **kwargs) -> None:\n    super(AutoEncoder, self).__init__(**kwargs)\n    self._encoder = Encoder(token_dim=token_dim, encoding_dim=encoding_dim, embedding_dim=embedding_dim, latent_dim=latent_dim, batch_dim=batch_dim)\n    self._decoder = Decoder(token_dim=token_dim, encoding_dim=encoding_dim, embedding_dim=embedding_dim, latent_dim=latent_dim, batch_dim=batch_dim)\n\n  def call(self, x: tf.Tensor) -> tf.Tensor:\n    return self._decoder(self._encoder(x))"""]

In [ ]:
# CACHE #######################################################################

__cache = llaminate.utils.create_cache(batch_dim=N_BATCH_DIM, cache_dim=N_CACHE_DIM, head_dim=N_HEAD_DIM, num_layers=N_LAYERS_NUM, num_heads=N_HEADS_NUM)
__step = 4

In [ ]:
# PREPROCESS ##################################################################

__prompt = SAMPLES[2]
__inputs = tokun.pipeline.preprocess(text=__prompt, groups=TOKUN_DIM, expand=N_SEQUENCE_AXIS * [1], flatten=True)

In [ ]:
# PREDICT #####################################################################

__predictions, _ = LLAMINATE(inputs=__inputs, cache=None, position=0, training=False, mask=None)
tokun.pipeline.postprocess(__predictions)

'                                                                                             o                                                    i                                                                                              o                                                                                                                                                                                                                                                                                                                          i                                                                   '

In [ ]:
__batch = iter(DATASET_TRAIN.batch(1))

In [ ]:
__x, __y = next(__batch)

In [ ]:
__p = LLAMINATE(inputs=__x, cache=None, position=0, training=True, mask=None)

__xt = tokun.pipeline.postprocess(tf.one_hot(__x, depth=256))
__yt = tokun.pipeline.postprocess(__y)
__yp = tokun.pipeline.postprocess(__p)

In [ ]:
print(tokun.evaluation.compare(__yt, __yp))
print(__yt)
print(__yp)

0.0
In Idaho, 472 people were asked what they call soft drinks. The results of the survey are shown in the pie chart. The central angle of the ``Pop'' sector of the graph is $251^\circ$, to the nearest whole degree. How many of the people surveyed chose ``Pop''? Express your answer as a whole number.

[asy]import graph;
size(150);
real w = 10pt,linew = 1;
filldraw(Arc((0,0),1,0,251)--(0,0)--cycle,gray(.4),black+linewidth(linew));
filldraw(Arc((0,0),1,251,280)--(0,0)--cycle,white,black+linewidth(linew));
filldraw(Arc((0,0),1,280,350)--(0,0)--cycle,gray(.7),black+linewidth(linew));
filldraw(Arc((0,0),1,350,360)--(0,0)--cycle,white,black+linewidth(linew));
label("\textbf{POP}",expi(2.19),expi(2.19),fontsize(w));
label("\textbf{COKE}",expi(4.63),expi(4.63),fontsize(w));
label("\textbf{SODA}",expi(5.50),expi(5.50),fontsize(w));
label("\textbf{OTHER}",expi(6.20),expi(6.20),fontsize(w));[/asy]We want to find the fraction of people that chose ``Pop". To this end, we find the fraction of the c

In [ ]:
tf.argmax(LLAMINATE._decoder(LLAMINATE._encoder(__x[:, :64])), axis=-1)

<tf.Tensor: shape=(1, 64), dtype=int64, numpy=
array([[  0,   0, 201, 131,   0,   0,   0,   0,   0,   0, 165, 123,   0,
          0,   0,  26,   0,   0,  68, 165,   0,   2, 252,  45,   0,   0,
         64,  32,   0,   0,  52,  79,   0,   0, 201,  98,   0,   0, 226,
        116,   0,   0,  15, 163,   0,   0,  52,  76,   0,   0, 192,  32,
          0,   2, 220,  43,   0,   0,  52,  59,   0,   0, 208,  44]])>

In [ ]:
__x[:, :64]

<tf.Tensor: shape=(1, 64), dtype=uint8, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=uint8)>

## Logs

In [ ]:
%tensorboard --logdir .logs